export const labels = {
  EN: {
    title: "LuminaGrid",
    sub: "Enterprise Fleet Control • Solar PV Central Node",
    operational: "OPERATIONAL",
    totalPower: "Total Power Output",
    activeUnits: "Active Units Count",
    weather: "Weather Status",
    fleet: "Inverter Units Fleet",
    reroute: "Execute Reroute",
    rerouting: "Rerouting...",
    systemLogs: "System Logs",
    aiAssistant: "AI Assistant",
    systemGuide: "System Guide",
    guide: "System Guide",
    export: "Export to Excel",
    close: "Close",
    guideTitle1: "1. Global AI Assistant",
    guideContent1: "The AI Assistant sidebar serves as your central command. Powered by LangChain, it reads the live telemetry context of the entire fleet. Ask it to summarize current operations or identify failing units. It can even generate interactive Action Cards inside the chat for instant approval.",
    guideTitle2: "2. Precision AI Diagnose & Isolation",
    guideContent2: "Click 'AI Diagnose' on any individual Unit Card to perform a deep-dive diagnostic utilizing RAG (Retrieval-Augmented Generation). The AI Diagnose modal now restricts actions based on real-time status—CRITICAL units can only be isolated. If the unit is deemed critically unstable, execute the 'Isolate Unit' command to override the telemetry stream and lock the unit offline securely.",
    guideTitle3: "3. Proactive Automated Co-Pilot",
    guideContent3: "LuminaGrid features an automated Weather Alert Co-Pilot that monitors external sensor data. When severe anomalies threaten efficiency, the Co-Pilot dynamically calculates a Split-Action Mitigation plan based on real-time unit states (e.g., isolating critical units while rerouting degraded ones).",
    exportConfirm: "Are you sure you want to export the current unit data and incident logs?",
    confirm: "Confirm",
    cancel: "Cancel",
    chatPlaceholder: "Ask AI Co-Pilot...",
    fullLogs: "Full System Activity Log",
    viewMore: "View All Units",
    viewLess: "Show Essential",
    rerouteSuccess: "Power redistribution complete. Efficiency restored.",
    exportSuccess: "Data exported successfully! Downloading Excel file...",
    searchPlaceholder: "Search ID or Status...",
    allUnits: "All Units",
    degraded: "Degraded",
    normal: "Normal",
    lastUpdatedText: "Last updated",
    rerouteConfirm: "Confirm rerouting 500kW load to Backup Battery to stabilize Units 12 & 15?",
    confirmExecution: "Confirm Execution"
  },
  ID: {
    title: "LuminaGrid",
    sub: "Kontrol Armada Enterprise • Node Terpusat Solar PV",
    operational: "BEROPERASI",
    totalPower: "Total Output Daya",
    activeUnits: "Unit Aktif",
    weather: "Status Cuaca",
    fleet: "Armada Inverter",
    reroute: "Eksekusi Pengalihan",
    rerouting: "Mengalihkan...",
    systemLogs: "Log Sistem",
    aiAssistant: "Asisten AI",
    systemGuide: "Panduan Sistem",
    guide: "Panduan Sistem",
    export: "Ekspor ke Excel",
    close: "Tutup",
    guideTitle1: "1. Asisten AI Global",
    guideContent1: "Bilah sisi Asisten AI berfungsi sebagai pusat komando Anda. Didukung oleh LangChain, asisten ini membaca konteks telemetri langsung dari seluruh armada. Minta asisten untuk merangkum operasi saat ini atau mengidentifikasi unit yang gagal. Asisten bahkan dapat menghasilkan Action Cards interaktif di dalam obrolan untuk persetujuan instan.",
    guideTitle2: "2. Diagnosis AI Presisi & Isolasi",
    guideContent2: "Klik 'AI Diagnose' pada Kartu Unit mana pun untuk melakukan diagnostik mendalam menggunakan RAG (Retrieval-Augmented Generation). Modal AI Diagnose sekarang membatasi tindakan berdasarkan status secara real-time—unit CRITICAL hanya dapat diisolasi. Jika unit dianggap sangat tidak stabil, eksekusi perintah 'Isolate Unit' untuk menimpa aliran telemetri dan mengunci unit secara offline dengan aman.",
    guideTitle3: "3. Co-Pilot Otomatis Proaktif",
    guideContent3: "LuminaGrid dilengkapi dengan Co-Pilot Peringatan Cuaca otomatis yang memantau data sensor eksternal. Ketika anomali cuaca mengancam efisiensi, Co-Pilot secara dinamis menghitung rencana Mitigasi Split-Action berdasarkan status unit secara real-time (misalnya, mengisolasi unit kritis sambil mengalihkan unit yang terdegradasi).",
    exportConfirm: "Apakah Anda yakin ingin mengekspor data unit dan log insiden saat ini?",
    confirm: "Konfirmasi",
    cancel: "Batal",
    chatPlaceholder: "Tanya AI Co-Pilot...",
    fullLogs: "Log Aktivitas Sistem Lengkap",
    viewMore: "Lihat Semua Unit",
    viewLess: "Tampilkan Esensial",
    rerouteSuccess: "Redistribusi daya selesai. Efisiensi pulih.",
    exportSuccess: "Data berhasil diekspor! Mengunduh file Excel...",
    searchPlaceholder: "Cari ID atau Status...",
    allUnits: "Semua Unit",
    degraded: "Degradasi",
    normal: "Normal",
    lastUpdatedText: "Terakhir diperbarui",
    rerouteConfirm: "Konfirmasi pengalihan beban 500kW ke Baterai Cadangan untuk menstabilkan Unit 12 & 15?",
    confirmExecution: "Konfirmasi Eksekusi"
  }
};
